customtab:
    enable: true
    updatedelay: 0
    header: "§bCyan§3World"
    footer: "§oCyanWorld.ru"
chattranslator:
    enable: false
fakebutitsrealonline:
    enable: false
    motd: "CyanWorld"
deathmsg:
    enable: true
joinmsg:
    enable: false
perworldchat:
    enable: false
perworldtab:
    enable: false
hubmode:
    enable: false
playerdeathanimation:
    enable: false
    respawndelay: 5
commands:
    spawn: false
    home: false
    sethome: false
reboot:
    time: "11:45"
messages:
    consoledeny: "§c» §rДанную команду нельзя выполнить через консоль"
    permdeny: "§c» §rУ тебя нет прав, чтобы выполнить эту команду"
    teleportdeny-otherworld: "§c» §rТелепортация в другой мир без портала невозможна!"
    teleporting: "§8» §rТелепортация..."
    sethome-needsleep: "§c» §rТы дожен поспать на кровати, чтобы установить точку дома"
    sethome-success: "§a» §rТочка дома установлена!"
